apiVersion: v1
kind: Service
metadata:
  name: <%= name %>
  labels:
    name: <%= name %>
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: <%= name %>
